version: 0.2

phases:
  install:
    commands:
      - gem install bundler jekyll
      - gem install jekyll-last-modified-at
      - gem install minima
  build:
    commands:
      - jekyll build
artifacts:
  name: deployable-site
  discard-paths: yes
  base-directory: _site