version: 0.2

phases:
  install:
    commands:
      - gem install bundler jekyll
      - gem install jekyll-last-modified-at
      - gem install minima
  build:
    commands:
      - jekyll build
      - aws s3 sync _site/ s3://abhishek.deydas.name
      - aws cloudfront create-invalidation --distribution-id E1PRO30G7BA7NW --paths *